Orders Api Integration
razorpay/razorpay-java-testapp pull request #1
Opened 2017-03-19 13:30 UTC by riagarg5

2017-03-19 15:40 UTC, ankit-rzp commented on pom.xml
> +  <repositories>
remove this

2017-03-19 15:41 UTC, ankit-rzp commented on pom.xml
> +      <version>1.2.0-SNAPSHOT</version>
if you have tested `1.2.0` then first release that, and use `1.2.0`, not the snapshot version

2017-03-19 15:41 UTC, ankit-rzp commented on src/main/java/com/razorpay/PaymentResource.java
> +    options.put("receipt", "txn_123456");
i dont think `receipt` is mandatory, check doc once.

2017-03-19 15:43 UTC, ankit-rzp commented on src/main/java/com/razorpay/PaymentResource.java
> +        if (isEqual) {
if not equal then throw exception

2017-03-19 15:45 UTC, ankit-rzp requested changes
Left comments. Also update the description, and use the correct formatter.

2017-03-20 04:40 UTC, mb-14 reviewed
Make the changes @ankit-rzp has requested. Otherwise LGTM.

2017-03-20 08:26 UTC, riagarg5 commented on src/main/java/com/razorpay/PaymentResource.java
> +    options.put("receipt", "txn_123456");
It is required

2017-03-20 08:30 UTC, riagarg5 commented on src/main/java/com/razorpay/PaymentResource.java
> +        if (isEqual) {
If not equal we are returning bad request

2017-03-20 08:39 UTC, ankit-rzp approved these changes
LGTM: But before you merge, please make sure version `1.2.0` is updated in mvn central

2017-03-21 07:00 UTC, merged